// <auto-generated />
using System;
using ColegioMilitar.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ColegioMilitar.Infrastructure.Migrations
{
    [DbContext(typeof(ColegioMilitarContext))]
    [Migration("20260316005250_AgregaPerdonada")]
    partial class AgregaPerdonada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("ColegioMilitar.Domain.Entities.ActitudMilitarManual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AñoAcademico")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bimestre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CadeteDNI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("NotaActitud")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CadeteDNI", "Bimestre", "AñoAcademico")
                        .IsUnique();

                    b.ToTable("ActitudesMilitares");
                });

            modelBuilder.Entity("ColegioMilitar.Domain.Entities.BimestreConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Año")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Bimestre")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Cerrada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreSemana")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NroSemana")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Bimestre", "Año", "NroSemana")
                        .IsUnique();

                    b.ToTable("BimestresConfig");
                });

            modelBuilder.Entity("ColegioMilitar.Domain.Entities.Cadete", b =>
                {
                    b.Property<string>("DNI")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApellidosNombres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Año")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Division")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.HasKey("DNI");

                    b.ToTable("Cadetes");
                });

            modelBuilder.Entity("ColegioMilitar.Domain.Entities.Castigo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nota")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PuntosAño3Raw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("0");

                    b.Property<string>("PuntosAño4Raw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("0");

                    b.Property<string>("PuntosAño5Raw")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("0");

                    b.Property<int>("Reincidencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("Codigo");

                    b.ToTable("Castigos");
                });

            modelBuilder.Entity("ColegioMilitar.Domain.Entities.Sancion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CadeteDNI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CastigoCodigo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsPierdeSalida")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Perdonada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PuntosAplicados")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SemanaBimestre")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupervisorDNI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CastigoCodigo");

                    b.HasIndex("Fecha");

                    b.HasIndex("SupervisorDNI");

                    b.HasIndex("CadeteDNI", "SemanaBimestre");

                    b.ToTable("Sanciones");
                });

            modelBuilder.Entity("ColegioMilitar.Domain.Entities.Supervisor", b =>
                {
                    b.Property<string>("DNI")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApellidosNombres")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Grado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("DNI");

                    b.ToTable("Supervisores");
                });

            modelBuilder.Entity("ColegioMilitar.Domain.Entities.ActitudMilitarManual", b =>
                {
                    b.HasOne("ColegioMilitar.Domain.Entities.Cadete", "Cadete")
                        .WithMany("ActitudesMilitares")
                        .HasForeignKey("CadeteDNI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cadete");
                });

            modelBuilder.Entity("ColegioMilitar.Domain.Entities.Sancion", b =>
                {
                    b.HasOne("ColegioMilitar.Domain.Entities.Cadete", "Cadete")
                        .WithMany("Sanciones")
                        .HasForeignKey("CadeteDNI")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ColegioMilitar.Domain.Entities.Castigo", "Castigo")
                        .WithMany("Sanciones")
                        .HasForeignKey("CastigoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ColegioMilitar.Domain.Entities.Supervisor", "Supervisor")
                        .WithMany("Sanciones")
                        .HasForeignKey("SupervisorDNI")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cadete");

                    b.Navigation("Castigo");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ColegioMilitar.Domain.Entities.Cadete", b =>
                {
                    b.Navigation("ActitudesMilitares");

                    b.Navigation("Sanciones");
                });

            modelBuilder.Entity("ColegioMilitar.Domain.Entities.Castigo", b =>
                {
                    b.Navigation("Sanciones");
                });

            modelBuilder.Entity("ColegioMilitar.Domain.Entities.Supervisor", b =>
                {
                    b.Navigation("Sanciones");
                });
#pragma warning restore 612, 618
        }
    }
}
